from themes import themecolor

theme = {'body_fg':themecolor['gray_666'],
				 'body_bg':themecolor['alice_blue'],
				 'a_link':themecolor['blue'],
				 'a_visited':themecolor['blue'],
				 'header_bg':themecolor['blue_4867d6'],
				 'header_bottom_border':themecolor['blue_266fad'],
				 'nav_main_bg':themecolor['blue_4867d6'],
				 'nav_main_fg':themecolor['red'],
				 'nav_main_border_top':themecolor['alice_blue'],
				 'nav_main_a_visited':themecolor['white'],
				 'nav_main_a_link':themecolor['white'],
				 'nav_main_a_hover':themecolor['red_pink_ec665d'],
				 'h2_color':themecolor['dark_blue'],
				 'sidebar_a_hover':themecolor['saphire'],
				 'footer_fg':themecolor['white'],
				 'footer_bg':themecolor['royal_blue'],
				 'footer_a_link':themecolor['white'],
				 'footer_a_visited':themecolor['white'],
				 'footer_a_hover':themecolor['light_gray_ddd'],
				 'course_details_bottom_border':themecolor['gray_aaa'],
				 'course_listing_a_link':themecolor['saphire'],
				 'course_listing_a_visited':themecolor['saphire'],
				 'course_listing_a_hover':themecolor['green_269926'],
				 'course_name':themecolor['blue_266fad'],
				 'topic_name':themecolor['blue_266fad'],
				 'course_description_a_visited':themecolor['skyblue_4eafae'],
				 'course_description_a_link':themecolor['skyblue_4eafae'],
				 'course_description_a_hover':themecolor['blue_266fad'],
				 'course_topics_a_link':themecolor['skyblue_4eafae'],
				 'course_topics_a_visited':themecolor['skyblue_4eafae'],
				 'course_topics_a_hover':themecolor['blue_266fad'],
				 'link_theme_b_a_link':themecolor['skyblue_4eafae'],
				 'link_theme_b_a_visited':themecolor['skyblue_4eafae'],
				 'link_theme_b_a_hover':themecolor['blue_266fad']}

