from themes import themecolor

theme = {'body_fg':themecolor['gray_666'],
				 'body_bg':themecolor['white'],
				 'a_link':themecolor['green_7b8614'],
				 'a_visited':themecolor['green_7b8614'],
				 'header_bg':themecolor['light_gray_fbfaf4'],
				 'header_bottom_border':themecolor['light_gray_ccc'],
				 'nav_main_bg':themecolor['gray_dedede'],
				 'nav_main_a_visited':themecolor['red_pink_ec665d'],
				 'nav_main_a_link':themecolor['red_pink_ec665d'],
				 'nav_main_a_hover':themecolor['red_pink_ec665d'],
				 'h2_color':themecolor['black'],
				 'sidebar_a_hover':themecolor['mil_green_316241'],
				 'footer_fg':themecolor['white'],
				 'footer_bg':themecolor['gray_666'],
				 'footer_a_link':themecolor['light_gray_ddd'],
				 'footer_a_visited':themecolor['light_gray_ddd'],
				 'footer_a_hover':themecolor['light_gray_ddd'],
				 'course_details_bottom_border':themecolor['gray_aaa'],
				 'course_listing_a_link':themecolor['gray_444'],
				 'course_listing_a_visited':themecolor['gray_444'],
				 'course_listing_a_hover':themecolor['gray_444'],
				 'course_name':themecolor['blue_266fad'],
				 'course_description_a_visited':themecolor['skyblue_4eafae'],
				 'course_description_a_link':themecolor['skyblue_4eafae'],
				 'course_description_a_hover':themecolor['blue_266fad'],
				 'course_topics_a_link':themecolor['skyblue_4eafae'],
				 'course_topics_a_visited':themecolor['skyblue_4eafae'],
				 'course_topics_a_hover':themecolor['blue_266fad'],
				 'link_theme_b_a_link':themecolor['skyblue_4eafae'],
				 'link_theme_b_a_visited':themecolor['skyblue_4eafae'],
				 'link_theme_b_a_hover':themecolor['blue_266fad']}

